version: '3.5'
services:

  elasticsearch:
    image: elasticsearch:8.4.1
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      - discovery.type=single-node
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker
        preferences:
          - spread: node.labels.region
          - spread: node.labels.host

